### PR TITLE
Updating ER and UML Diagram

### PR DESCRIPTION
**Pull request by Bento007**
partial fix for https://github.com/chanzuckerberg/corpora-data-portal/issues/636

### CODE REVIEW

**Comment by MDunitz** [comment]
Hey!
Couple of quick questions from comparing the diagrams to each other and the orm code changes (lots of nits)
- it looks like link type on projectLinks is missing the summary enum
- I wasnt able to find the TC_URI on the ER diagram
- What do the double circles on the ER diagram mean?
- In the code the dataset columns are jsonb and organism vs organism and organism ontology on the diagrams (also labeled as a string on the urm diagram)
- The ER dataset diagram has `disease state` vs `disease` in the code/urm
- The ER dataset diagram seems to be missing `development state`
- The ER & URM diagrams have `Is_valid` as a boolean but the code shows it as an enum `ValidationType`
- Could you change DatasetContributors to DatasetContributorLink?
- In the code DatasetArtifacts also has a `user_submitted` field (not shown in either diagram)
- In the URM there is a `DatasetArtifacts` table but in the ER its called `Dataset_Asset`
- The ER diagram uses `format` instead of `filetype` (on the dataset_asset)
- The DeploymentDirectory table only had one url but the urm has 2
- The dataset ER diagram refers to `title` but the code/urm use `name`
- The way citations/doi are represented in the er diagram didnt match the code/urm diagram

**Comment by Bento007** [comment]
@MDunitz 
>it looks like link type on projectLinks is missing the summary enum

What is the summary Enum?

**Comment by Bento007** [comment]
>What do the double circles on the ER diagram mean?

@maniarathi  do you know?

**Comment by Bento007** [comment]
> The ER & URM diagrams have Is_valid as a boolean but the code shows it as an enum ValidationType

@MDunitz I'm not see this any where?

**Comment by Bento007** [comment]
> Could you change DatasetContributors to DatasetContributorLink?

@MDunitz why is this needed?

**Comment by Bento007** [comment]
> The way citations/doi are represented in the er diagram didnt match the code/urm diagram

@MDunitz I deffer that one to @maniarathi. If were are making the diagrams reflect reality then it should be moved into the dataset, but this could also be representing future plans.

**Comment by brianraymor** [comment]
@Bento007 and @mckinsel - while you're updating the model - you may also want to consider - 
[The database model must include number of cells per dataset](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/635)

**Comment by maniarathi** [comment]
> > What do the double circles on the ER diagram mean?
> 
> @maniarathi do you know?

Multi-valued attribute.

**Comment by maniarathi** [comment]
> > The way citations/doi are represented in the er diagram didnt match the code/urm diagram
> 
> @MDunitz I deffer that one to @maniarathi. If were are making the diagrams reflect reality then it should be moved into the dataset, but this could also be representing future plans.

@mckinsel Did I miss changes in this ticket reflect that DOI should be associated with a Collection? Is this an additional database change that needs to occur?

**Comment by brianraymor** [comment]
@maniarathi - DOI is now modeled as a link type for Collections:

- Optional Links of type `DOI`, `Raw Data`, `Protocol`, `Lab Website`, or `Other`

Also see [Refinements to schema](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/75)- the schema and the model should be updated simultaneously.

**Comment by MDunitz** [comment]
> @MDunitz
> 
> > it looks like link type on projectLinks is missing the summary enum
> 
> What is the summary Enum?

https://github.com/chanzuckerberg/corpora-data-portal/pull/670/files#diff-e1c5f0a85e4ae32019af86ea4e8d9c1abb18edf76ffa9c9713f55a645482122eR131

**Comment by MDunitz** [comment]
> > Could you change DatasetContributors to DatasetContributorLink?
> 
> @MDunitz why is this needed?

I like to use it to indicate that its a table to support a many to many relationship between two other tables. Probably not required.

**Comment by brianraymor** [comment]
> What is the summary Enum?

It's deprecated - see [Refinements to schema](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell/75):

_We also agreed that the UX would **not** support the `SUMMARY` link_type because it is no longer required by hosted cellxgene._

**Comment by mckinsel** [comment]
Is there a version of the schema associated with this? Some of it could [change](https://github.com/chanzuckerberg/corpora-data-portal/pull/672) a little.

**Comment by MDunitz** [comment]
it looks like the er diagram is still missing development state? Also nit but would it be possible to sort of stack the ontology with its object. I think it would add clarity and space. I appreciate that the ontology in the er is there to indicate that we are calculating that field based on what the user input but I think the connection could be more clear if (for example) the organism oval was half over the organism ontology circle. Does that make sense?

Other questions 
- are you going to create another pr to update project -> collection?
- it looks like `tc_uri` has been removed from the code and replaced with `data_submission_policy_version`

**Review by mckinsel — CHANGES_REQUESTED** [review]
So if the goal for this is to reflect current or near-future state, I think a bunch of stuff has to change:

- Remove contributor table from ER and UML, and DatasetContributors from UML
- Remove DOI entity, make DOI-link an attribute of project
- Remove DOI fields from dataset table in UML
- Remove "Remix or Original" from artifact in ER and Type from artifact table in UML
- Remove "alias url" and "original url" from deployment_directory in UML and replace with just "url"
- Change type of sex to JSONB in UML
- Add "contact_email" "contact_name" to project
- Remove attestation_link and needs_attestation from project
- Add data_submission_policy_version to project
- Remove tc_uri from project

**Review by mckinsel — APPROVED** [review]
A few small changes, but otherwise LGTM

in Dataset
- sex is JSONB
- ethnicity is misspelled

In ProjectLink:
link_type is Enum(Doi, Lab_Website, Other, Protocol, Raw_Data)

If you want to stick them in, the statuses are
upload: Enum{Canceled, Cancel_Pending, Failed, NA, Uploaded, Uploading, Waiting}
validation: Enum{Invalid, NA, Valid, Validating}
conversion: Enum{Converted, Converting, Failed, NA}

**Comment by maniarathi** [comment]
Oh man, sorry about that. I left the enums blank as a "reminder" that I needed to fill them in by looking at the code :P Thanks for catching the mistakes!

**Pull request merged**
