### PR TITLE
Brief document that provides context on splitting the cellxgene desktop and czi-hosted backends.

### PR DESCRIPTION
**Pull request by mckinsel**

### CODE REVIEW

**Comment by brianraymor** [comment]
@maniarathi - what should happen with this PR?

**Comment by maniarathi** [comment]
I think we should keep this as a "motivation" or "informational RFC" type of doc and check it in. I'm going to make some modifications to clean it up and then will formally request review.

**Comment by maniarathi** [comment]
Will aim to clean up by Wednesday

**Review by Bento007 — APPROVED** [review]

**Review by MDunitz — APPROVED** [review]
lgtm

**Pull request merged**
